[project]
name = "one_fm_password_management"
authors = [
    { name = "ONE FM", email = "develop@one-fm.com" }
]
description = "Password Management"
requires-python = ">=3.10"
readme = "README.md"
dynamic = ["version"]

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

[tool.bench.frappe-dependencies]
frappe = ">=16.0.0"
